# Generated by Django 5.2.3 on 2025-06-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='nombre_madre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='miembro',
            name='nombre_padre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='miembro',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=10),
        ),
    ]
