# Generated by Django 5.2.3 on 2025-06-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0002_miembro_nombre_madre_miembro_nombre_padre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='iglesia',
            field=models.CharField(choices=[('Central', 'Iglesia Central'), ('Tekera', 'Filial La Tekera'), ('Pital', 'Filial El Pital'), ('Sauce', 'Filial El Sauce')], default='Central', max_length=20),
        ),
    ]
