# Generated by Django 5.2.3 on 2025-06-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0003_miembro_iglesia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='nombre_madre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='nombre_padre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
