# Generated by Django 5.2.3 on 2025-06-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0004_alter_miembro_cargo_alter_miembro_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='nombre_conyugue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Casado', 'Casado'), ('Acompañado', 'Acompañado')], max_length=20, null=True),
        ),
    ]
