# Generated by Django 5.2.3 on 2025-06-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0005_miembro_nombre_conyugue_alter_miembro_estado_civil'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='cantidad_hijos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miembro',
            name='nombres_hijos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Casado', 'Casado'), ('Acompañado', 'Acompañado'), ('Viudo', 'Viudo')], max_length=20, null=True),
        ),
    ]
