# Generated by Django 5.2.3 on 2025-06-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0006_miembro_cantidad_hijos_miembro_nombres_hijos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='otros_cargos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
